# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'testappcenter' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for testappcenter

  

  platform :ios, '9.0'
  target 'testappcenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'testappcenter-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testappcenter-tvOS

  target 'testappcenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
